### ISSUE TITLE
Statistiken

### ISSUE THREAD

**Issue by Birgauan09** [TGM-HIT/sew9-2324-worttrainer-jbekhet#1]
Sehr geehrter Programmierer!

Bei der Benutzung deines Programmes habe ich einen (Fehler) bemerkt. Deine Statistik-Anzeige gefällt mir nicht, bzw. ich verstehe sie nicht. Könntest du das verständlicher machen, sehr geehrter Programmierer.

Mit freundlichen Grüßen,
Issue-Giver

**Comment by jbekhet** [comment]
Sehr geehrter Herr  Issue-Giver,

vielen Dank für den Issue.  Dieser wurde verbessert und es wurrde darauf geachtet die Statistik besser zu veranschauen.

Nochmals danke.

Mit freundlichen Grüßen,
Der Programmierer
